### ISSUE TITLE
ArgumentError: unknown keywords: hostname, address, interface and other params

### ISSUE THREAD

**Issue by vsingh-msys** [chef-cookbooks/aix#119]
it raises `ArgumentError` when any properties defined for aix_wpar custom resource.

```
FATAL: ArgumentError: aix_wpar[testwpar2] (aix::default line 1) had an error: ArgumentError: unknown keywords: hostname, address, interface, rootvg, rootvg_disk, wparvg, backupimage, cpu, memory, autostart, wpar_state, live_stream, name, before, params, provider, allowed_actions, action, updated, updated_by_last_action, source_line, guard_interpreter, default_guard_interpreter, elapsed_time, exists

```

### Cookbook version

2.3.2

### Chef-client version

chef-client 14, 15, 16

### Platform Details

AIX 7.1

### Scenario:

Tying to run the recipe on AIX LPAR host
```
aix_wpar 'create wpar' do
 action :create
 name 'testwpar2'
 hostname 'testwpar2'
 cpu '10%-50%,100%'
 live_stream true
 autostart true
end
```

### Expected Result:

It should create the WPAR with provided recipe detail.

### Actual Result:

```
$ sudo chef-client -z -o 'recipe[aix::default]'
/opt/chef/embedded/lib/ruby/gems/2.7.0/gems/ed25519-1.2.4/lib/ed25519.rb:13: warning: already initialized constant Ed25519::KEY_SIZE
/opt/chef/embedded/lib/ruby/gems/2.7.0/gems/ed25519-1.2.4/lib/ed25519.rb:13: warning: previous definition of KEY_SIZE was here
/opt/chef/embedded/lib/ruby/gems/2.7.0/gems/ed25519-1.2.4/lib/ed25519.rb:16: warning: already initialized constant Ed25519::SIGNATURE_SIZE
/opt/chef/embedded/lib/ruby/gems/2.7.0/gems/ed25519-1.2.4/lib/ed25519.rb:16: warning: previous definition of SIGNATURE_SIZE was here
/opt/chef/embedded/lib/ruby/gems/2.7.0/gems/ed25519-1.2.4/lib/ed25519.rb:19: warning: already initialized constant Ed25519::VerifyError
/opt/chef/embedded/lib/ruby/gems/2.7.0/gems/ed25519-1.2.4/lib/ed25519.rb:19: warning: previous definition of VerifyError was here
/opt/chef/embedded/lib/ruby/gems/2.7.0/gems/ed25519-1.2.4/lib/ed25519.rb:22: warning: already initialized constant Ed25519::SelfTestFailure
/opt/chef/embedded/lib/ruby/gems/2.7.0/gems/ed25519-1.2.4/lib/ed25519.rb:22: warning: previous definition of SelfTestFailure was here
/opt/chef/embedded/lib/ruby/gems/2.7.0/gems/ed25519-1.2.4/lib/ed25519.rb:13: warning: already initialized constant Ed25519::KEY_SIZE
/opt/chef/embedded/lib/ruby/gems/2.7.0/gems/ed25519-1.2.4/lib/ed25519.rb:13: warning: previous definition of KEY_SIZE was here
/opt/chef/embedded/lib/ruby/gems/2.7.0/gems/ed25519-1.2.4/lib/ed25519.rb:16: warning: already initialized constant Ed25519::SIGNATURE_SIZE
/opt/chef/embedded/lib/ruby/gems/2.7.0/gems/ed25519-1.2.4/lib/ed25519.rb:16: warning: previous definition of SIGNATURE_SIZE was here
/opt/chef/embedded/lib/ruby/gems/2.7.0/gems/ed25519-1.2.4/lib/ed25519.rb:19: warning: already initialized constant Ed25519::VerifyError
/opt/chef/embedded/lib/ruby/gems/2.7.0/gems/ed25519-1.2.4/lib/ed25519.rb:19: warning: previous definition of VerifyError was here
/opt/chef/embedded/lib/ruby/gems/2.7.0/gems/ed25519-1.2.4/lib/ed25519.rb:22: warning: already initialized constant Ed25519::SelfTestFailure
/opt/chef/embedded/lib/ruby/gems/2.7.0/gems/ed25519-1.2.4/lib/ed25519.rb:22: warning: previous definition of SelfTestFailure was here
/opt/chef/embedded/lib/ruby/gems/2.7.0/gems/ed25519-1.2.4/lib/ed25519.rb:13: warning: already initialized constant Ed25519::KEY_SIZE
/opt/chef/embedded/lib/ruby/gems/2.7.0/gems/ed25519-1.2.4/lib/ed25519.rb:13: warning: previous definition of KEY_SIZE was here
/opt/chef/embedded/lib/ruby/gems/2.7.0/gems/ed25519-1.2.4/lib/ed25519.rb:16: warning: already initialized constant Ed25519::SIGNATURE_SIZE
/opt/chef/embedded/lib/ruby/gems/2.7.0/gems/ed25519-1.2.4/lib/ed25519.rb:16: warning: previous definition of SIGNATURE_SIZE was here
/opt/chef/embedded/lib/ruby/gems/2.7.0/gems/ed25519-1.2.4/lib/ed25519.rb:19: warning: already initialized constant Ed25519::VerifyError
/opt/chef/embedded/lib/ruby/gems/2.7.0/gems/ed25519-1.2.4/lib/ed25519.rb:19: warning: previous definition of VerifyError was here
/opt/chef/embedded/lib/ruby/gems/2.7.0/gems/ed25519-1.2.4/lib/ed25519.rb:22: warning: already initialized constant Ed25519::SelfTestFailure
/opt/chef/embedded/lib/ruby/gems/2.7.0/gems/ed25519-1.2.4/lib/ed25519.rb:22: warning: previous definition of SelfTestFailure was here
[2020-05-08T17:17:05+00:00] WARN: No config file found or specified on command line. Using command line options instead.
Starting Chef Infra Client, version 16.0.287
[2020-05-08T17:17:14+00:00] WARN: Run List override has been provided.
[2020-05-08T17:17:14+00:00] WARN: Original Run List: []
[2020-05-08T17:17:14+00:00] WARN: Overridden Run List: [recipe[aix::default]]
resolving cookbooks for run list: ["aix::default"]
Synchronizing Cookbooks:
  - aix (2.3.2)
Installing Cookbook Gems:
Compiling Cookbooks...
Converging 1 resources
Recipe: aix::default
  * aix_wpar[testwpar] action create/.chef/local-mode-cache/cache/cookbooks/aix/providers/wpar.rb:53: warning: Using the last argument as keyword parameters is deprecated; maybe ** should be added to the call
/opt/chef/embedded/lib/ruby/gems/2.7.0/gems/mixlib-log-3.0.8/lib/mixlib/log/logging.rb:46: warning: The called method is defined here
    ================================================================================
    Error executing action `create` on resource 'aix_wpar[testwpar]'
    ================================================================================
    ArgumentError
    -------------
    unknown keywords: :hostname, :address, :interface, :rootvg, :rootvg_disk, :wparvg, :backupimage, :cpu, :memory, :autostart, :wpar_state, :live_stream, :name, :before, :params, :provider, :allowed_actions, :action, :updated, :updated_by_last_action, :source_line, :guard_interpreter, :default_guard_interpreter, :elapsed_time, :exists
    Cookbook Trace:
    ---------------
    /.chef/local-mode-cache/cache/cookbooks/aix/providers/wpar.rb:53:in `load_current_resource'
    Resource Declaration:
    ---------------------
    # In /.chef/local-mode-cache/cache/cookbooks/aix/recipes/default.rb
      1: aix_wpar 'create wpar' do
      2:   action :create
      3:   name 'testwpar'
      4:   hostname 'testwpar'
      5:   address '172.31.10.29'
      6:   interface 'en0'
      7:   wparvg 'scratchvg'
      8:   cpu '10%-50%,100%'
      9:   live_stream true
     10:   autostart true
     11: end
    Compiled Resource:
    ------------------
    # Declared in /.chef/local-mode-cache/cache/cookbooks/aix/recipes/default.rb:1:in `from_file'
    aix_wpar("testwpar") do
      action [:create]
      default_guard_interpreter :default
      declared_type :aix_wpar
      cookbook_name "aix"
      recipe_name "default"
      hostname "testwpar"
      interface "en0"
      wparvg "scratchvg"
      cpu "10%-50%,100%"
      live_stream true
      autostart true
    end
    System Info:
    ------------
    chef_version=16.0.287
    platform=aix
    platform_version=7.2
    ruby=ruby 2.7.1p83 (2020-03-31 revision a0c7c23c9c) [powerpc-aix7.1.5.0]
    program_name=/opt/chef/bin/chef-client
    executable=/opt/chef/bin/chef-client
Running handlers:
[2020-05-08T17:17:20+00:00] ERROR: Running exception handlers
Running handlers complete
[2020-05-08T17:17:20+00:00] ERROR: Exception handlers complete
Chef Infra Client failed. 0 resources updated in 12 seconds
[2020-05-08T17:17:20+00:00] FATAL: Stacktrace dumped to /.chef/local-mode-cache/cache/chef-stacktrace.out
[2020-05-08T17:17:20+00:00] FATAL: Please provide the contents of the stacktrace.out file if you file a bug report
[2020-05-08T17:17:20+00:00] FATAL: ArgumentError: aix_wpar[testwpar] (aix::default line 1) had an error: ArgumentError: unknown keywords: :hostname, :address, :interface, :rootvg, :rootvg_disk, :wparvg, :backupimage, :cpu, :memory, :autostart, :wpar_state, :live_stream, :name, :before, :params, :provider, :allowed_actions, :action, :updated, :updated_by_last_action, :source_line, :guard_interpreter, :default_guard_interpreter, :elapsed_time, :exists
```

**Comment by vsingh-msys** [comment]
As dicussed in slack issue will get resolve by changing `attribute` to `property` of custom resources.
