### ISSUE TITLE
integration tests for aix cookbooks

### ISSUE THREAD

**Issue by jkleinlercher** [chef-cookbooks/aix#28]
Hi,

I looked at the cookbook but can't find any hint how I can do integration tests with this cookbook. There is a link to https://github.com/chef-cookbooks/aix/blob/master/TESTING.md but there you refer to vagrant and virtualbox and thats of course not applicable to AIX cookbooks.

I also asked this question on http://stackoverflow.com/questions/36053361/kitchen-tests-with-aix but it seems there is currently no way to do integration tests which makes me feel that developing and testing AIX cookbooks is not possible in a convenient way like Linux cookbooks.
I would really appreciate if you can describe how you do integration tests and/or participate in the discussion on http://stackoverflow.com/questions/36053361/kitchen-tests-with-aix .

Thanks in advance!

**Comment by adejoux** [comment]
Hello,

You are right we are still lacking on the test part here.

I made a test kitchen driver for WPAR. 
Code is available here:  https://github.com/adejoux/kitchen-wpar

It's published on RubyGems, from chef-dk, you can install it with:
**chef gem install kitchen-wpar**

I also made a pull request to add test kitchen tests in this cookbook.

An example of kitchen converge:

````
➜  aix git:(master) ✗ kitchen converge
-----> Starting Kitchen (v1.6.0)
-----> Converging <default-wpar>...
       Preparing files for transfer
       Preparing dna.json
       Resolving cookbook dependencies with Berkshelf 4.3.0...
       Removing non-cookbook files before transfer
       Preparing solo.rb
       Transferring files to <default-wpar>
       [2016-04-10T07:46:48-05:00] WARN: Please install an English UTF-8 locale for Chef to use, falling back to C locale and disabling UTF-8 support.
       Starting Chef Client, version 12.8.1
       Installing Cookbook Gems:
       Compiling Cookbooks...
       [2016-04-10T07:46:57-05:00] WARN: Cloning resource attributes for aix_etchosts[test] from prior resource (CHEF-3694)
       [2016-04-10T07:46:57-05:00] WARN: Previous aix_etchosts[test]: /tmp/kitchen/cookbooks/aix/recipes/default.rb:33:in `from_file'
       [2016-04-10T07:46:57-05:00] WARN: Current  aix_etchosts[test]: /tmp/kitchen/cookbooks/aix/recipes/default.rb:38:in `from_file'
       [2016-04-10T07:46:57-05:00] WARN: Cloning resource attributes for aix_etchosts[test] from prior resource (CHEF-3694)
       [2016-04-10T07:46:57-05:00] WARN: Previous aix_etchosts[test]: /tmp/kitchen/cookbooks/aix/recipes/default.rb:38:in `from_file'
       [2016-04-10T07:46:57-05:00] WARN: Current  aix_etchosts[test]: /tmp/kitchen/cookbooks/aix/recipes/default.rb:43:in `from_file'
       [2016-04-10T07:46:57-05:00] WARN: Cloning resource attributes for aix_etchosts[test] from prior resource (CHEF-3694)
       [2016-04-10T07:46:57-05:00] WARN: Previous aix_etchosts[test]: /tmp/kitchen/cookbooks/aix/recipes/default.rb:43:in `from_file'
       [2016-04-10T07:46:57-05:00] WARN: Current  aix_etchosts[test]: /tmp/kitchen/cookbooks/aix/recipes/default.rb:48:in `from_file'
       [2016-04-10T07:46:57-05:00] WARN: Cloning resource attributes for aix_etchosts[test] from prior resource (CHEF-3694)
       [2016-04-10T07:46:57-05:00] WARN: Previous aix_etchosts[test]: /tmp/kitchen/cookbooks/aix/recipes/default.rb:48:in `from_file'
       [2016-04-10T07:46:57-05:00] WARN: Current  aix_etchosts[test]: /tmp/kitchen/cookbooks/aix/recipes/default.rb:54:in `from_file'
       Converging 11 resources
       Recipe: aix::default
         * user[foobar] action create
           - create user foobar
         * aix_inittab[my-awesome-aix-daemon] action install
           - Install or update inittab
         * aix_subserver[tftp] action disable (up to date)
         * aix_tcpservice[xntpd] action enable
           - enable TCP/IP service
         * aix_chsec[/etc/security/login.cfg] action update
           - chsec: changing /etc/security/login.cfg for stanza usw
         * aix_etchosts[test] action add
           - hostent: add test in /etc/hosts file
         * aix_etchosts[test] action change
           - etchost: modifying test in /etc/hosts
         * aix_etchosts[test] action change
           - etchost: modifying test in /etc/hosts
         * aix_etchosts[test] action add
           - hostent: add test in /etc/hosts file
         * aix_etchosts[test] action delete
           - hostent: delete 1.1.1.1
         * aix_etchosts[delete all entries] action delete_all
           - etchost: removing all entries
       
       Running handlers:
       Running handlers complete
       Chef Client finished, 10/11 resources updated in 07 seconds
       Finished converging <default-wpar> (0m35.49s).
-----> Kitchen is finished. (0m35.92s)
`````

All comments are welcome :)

**Comment by chmod666org** [comment]
Doing the same for powervc.
Will publish soon.
Awesome job !

**Comment by adejoux** [comment]
Great :). PowerVC will be the best testing solution. wpar is nice when users don't have it :)

**Comment by chmod666org** [comment]
Right, unfortunately testing on a wpar will not be enough to test all the providers (tunables, updates ... and so on) but it's a very good start.
I've forked the kitchen-openstack to kitchen-powervc it's almost working but still need to add more options.
Fantastic job Alain ! :)

**Comment by chmod666org** [comment]
Kitchen-powervc also available (https://github.com/chmod666org/kitchen-powervc)
You now have two solutions for testing PowerVC or wpar.
Closing issue.
