### ISSUE TITLE
aix_chdev fails for hdisk1 queue_depth in version 1.0.0 but not with version 0.1.0

### ISSUE THREAD

**Issue by jkohlmeier** [chef-cookbooks/aix#55]
### Cookbook version
1.0.0 fails. works in 0.1.0

### Chef-client version
12.18.49

### Platform Details
AIX 7.1 TL3

### Scenario:
Trying to test my oracle_ebs cookbook with the latest AIX. 1.1.0 fails with wpar issue.
So back-tracking to 1.0.0. It fails on changing the hdisk queue_depth field. Doesnt
recognize queue_depth.

### Steps to Reproduce:
aix_chdev "hdisk1_queue_depth" do
  name "hdisk1"
  attributes(:queue_depth => 64 )
  action :update
  not_if "lspv hdisk1"
end

### Expected Result:
(version 0.1.0)
p135n52.pbm.ihost.com Converging 1 resources
p135n52.pbm.ihost.com Recipe: oracle_ebs::test1
p135n52.pbm.ihost.com   * aix_chdev[hdisk1] action update
p135n52.pbm.ihost.com     - chdev device hdisk1 with {:queue_depth=>60}
p135n52.pbm.ihost.com 
p135n52.pbm.ihost.com Running handlers: 

### Actual Result:
 
p135n52.pbm.ihost.com     RuntimeError
p135n52.pbm.ihost.com     ------------
p135n52.pbm.ihost.com     chdev device hdisk1 has not attribute queue_depth
p135n52.pbm.ihost.com     
p135n52.pbm.ihost.com     Cookbook Trace:
p135n52.pbm.ihost.com     ---------------
p135n52.pbm.ihost.com     /var/chef/cache/cookbooks/aix/providers/chdev.rb:88:in `block (2 levels) in class_from_file'
p135n52.pbm.ihost.com     /var/chef/cache/cookbooks/aix/providers/chdev.rb:72:in `each'
p135n52.pbm.ihost.com     /var/chef/cache/cookbooks/aix/providers/chdev.rb:72:in `block in class_from_file'
p135n52.pbm.ihost.com     
p135n52.pbm.ihost.com     Resource Declaration:
p135n52.pbm.ihost.com     ---------------------
p135n52.pbm.ihost.com     # In /var/chef/cache/cookbooks/oracle_ebs/recipes/test1.rb
p135n52.pbm.ihost.com     
p135n52.pbm.ihost.com       1: aix_chdev "hdisk1_queue_depth" do
p135n52.pbm.ihost.com       2:   name "hdisk1"
p135n52.pbm.ihost.com       3:   attributes(:queue_depth => 60 )
p135n52.pbm.ihost.com       4:   action :update
p135n52.pbm.ihost.com       5:   not_if "lspv hdisk1"
p135n52.pbm.ihost.com       6: end
p135n52.pbm.ihost.com     
p135n52.pbm.ihost.com     Compiled Resource:
p135n52.pbm.ihost.com     ------------------
p135n52.pbm.ihost.com     # Declared in /var/chef/cache/cookbooks/oracle_ebs/recipes/test1.rb:1:in `from_file'

**Comment by jkohlmeier** [comment]
Tested issue with AIX cookbook 1.2.0. Problem is not reproducible now. So Assume this is fixed in this version.
