### ISSUE TITLE
Error with altdisk.rb

### ISSUE THREAD

**Issue by brandoncallah** [chef-cookbooks/aix#66]
### Chef-client version
Chef: 12.18.31

### Platform Details
DISTRIB_ID=Ubuntu
DISTRIB_RELEASE=14.04
DISTRIB_CODENAME=trusty
DISTRIB_DESCRIPTION="Ubuntu 14.04.4 LTS"
NAME="Ubuntu"
VERSION="14.04.4 LTS, Trusty Tahr"

### Scenario:
I am trying to get the cookbooks working that I downloaded from github on AIX 6.1 (https://github.com/chef-cookbooks/aix) . My goal is to eventually migrate from 6.1 to 7.1.4. Any guidance to the problem below would be greatly appreciated as I’m at a standstill on this issue.
The issue appears to be in the code or something is not being defined that way it’s supposed to when the code runs:
Lines 63 and 68 from providers/altdisk.rb…appears to be this block of code causing the issue. You can see the highlighted error down below.
```

if disk != 'None'
Chef::Log.debug("alt_disk: we found a disk #{disk}")
converge_by("alt_disk: creating alternate rootvg disk name #{@new_resource.altdisk_name} on disk #{disk}") do
alt_disk_copy_str = "alt_disk_copy -d #{disk}"
unless @new_resource.change_bootlist
alt_disk_copy_str = alt_disk_copy_str << ' -B '
end
if @new_resource.reset_devices
alt_disk_copy_str = alt_disk_copy_str << ' -O '
end
if @new_resource.remain_nimclient
alt_disk_copy_str = alt_disk_copy_str << ' -n '
end
Chef Development Kit Version: 1.2.20
chef-client version: 12.18.31
delivery version: master (0b746cafed65a9ea1a79de3cc546e7922de9187c)
berks version: 5.5.0
kitchen version: 1.15.0
I am trying to get a simple recipe working for an alt_disk_copy.
Cat chef-repo/cookbooks/aix/recipes/
aix_altdisk 'altdisk_by_auto' do
type :auto
value 'equal'
change_bootlist true
action :create
end
root@fittestaix1(/etc/chef/ohai_plugins)$ lspv
hdisk0 00fa9a4242f176f9 rootvg active
hdisk1 00fa9a425da26eac None
I am running the following command line. The alt_disk.rb recipe is in the run list.
Node Name: fittestaix1
Environment: _default
FQDN: fittestaix1
IP: redacted
Run List: recipe[aix::altdisk]
Roles:
Recipes: aix::altdisk
Platform: aix 6.1
Tags:
sudo knife ssh "name:fittestaix1" 'chef-client -l info' -x root
fittestaix1 * aix_altdisk[altdisk_by_auto] action create[2017-02-21T10:10:51-06:00] INFO: Processing aix_altdisk[altdisk_by_auto] action create (aix::altdisk line 1)
fittestaix1
fittestaix1 ================================================================================
fittestaix1 Error executing action `create` on resource 'aix_altdisk[altdisk_by_auto]'
fittestaix1 ================================================================================
fittestaix1
fittestaix1 NoMethodError
fittestaix1 -------------
fittestaix1 undefined method `reset_devices' for Custom resource aix_altdisk from cookbook aix
fittestaix1
fittestaix1 Cookbook Trace:
fittestaix1 ---------------
fittestaix1 /var/chef/cache/cookbooks/aix/providers/altdisk.rb:68:in `block (2 levels) in class_from_file'
fittestaix1 /var/chef/cache/cookbooks/aix/providers/altdisk.rb:63:in `block in class_from_file'
fittestaix1
fittestaix1 Resource Declaration:
fittestaix1 ---------------------
fittestaix1 # In /var/chef/cache/cookbooks/aix/recipes/altdisk.rb
fittestaix1
fittestaix1 1: aix_altdisk 'altdisk_by_auto' do
fittestaix1 2: type :auto
fittestaix1 3: value 'equal'
fittestaix1 4: change_bootlist true
fittestaix1 5: action :create
fittestaix1 6: end
fittestaix1
fittestaix1 Compiled Resource:
fittestaix1 ------------------
fittestaix1 # Declared in /var/chef/cache/cookbooks/aix/recipes/altdisk.rb:1:in `from_file'
fittestaix1
fittestaix1 aix_altdisk("altdisk_by_auto") do
fittestaix1 action [:create]
fittestaix1 retries 0
fittestaix1 retry_delay 2
fittestaix1 default_guard_interpreter :default
fittestaix1 declared_type :aix_altdisk
fittestaix1 cookbook_name "aix"
fittestaix1 recipe_name "altdisk"
fittestaix1 type :auto
fittestaix1 value "equal"
fittestaix1 change_bootlist true
fittestaix1 altdisk_name "altinst_rootvg"
fittestaix1 end
fittestaix1
fittestaix1 Platform:
fittestaix1 ---------
fittestaix1 powerpc-aix6.1.0.0
fittestaix1
fittestaix1 [2017-02-21T10:10:52-06:00] INFO: Running queued delayed notifications before re-raising exception
fittestaix1
fittestaix1 Running handlers:
fittestaix1 [2017-02-21T10:10:52-06:00] ERROR: Running exception handlers
fittestaix1 Running handlers complete
fittestaix1 [2017-02-21T10:10:52-06:00] ERROR: Exception handlers complete
fittestaix1 Chef Client failed. 0 resources updated in 08 seconds
fittestaix1 [2017-02-21T10:10:52-06:00] FATAL: Stacktrace dumped to /var/chef/cache/chef-stacktrace.out
fittestaix1 [2017-02-21T10:10:52-06:00] FATAL: Please provide the contents of the stacktrace.out file if you file a bug report
fittestaix1 [2017-02-21T10:10:52-06:00] ERROR: aix_altdisk[altdisk_by_auto] (aix::altdisk line 1) had an error: NoMethodError: undefined method `reset_devices' for Custom resource aix_altdisk from cookbook aix
fittestaix1 [2017-02-21T10:10:52-06:00] FATAL: Chef::Exceptions::ChildConvergeError: Chef run process exited unsuccessfully (exit code 1)

if disk != 'None'
Chef::Log.debug("alt_disk: we found a disk #{disk}")
converge_by("alt_disk: creating alternate rootvg disk name #{@new_resource.altdisk_name} on disk #{disk}") do
alt_disk_copy_str = "alt_disk_copy -d #{disk}"
#unless @new_resource.change_bootlist
# alt_disk_copy_str = alt_disk_copy_str << ' -B '
#end
#if @new_resource.reset_devices
# alt_disk_copy_str = alt_disk_copy_str << ' -O '
#end
#if @new_resource.remain_nimclient
# alt_disk_copy_str = alt_disk_copy_str << ' -n '
#end
```

### Steps to Reproduce:
I am trying to get a simple recipe working for an alt_disk_copy.
Cat chef-repo/cookbooks/aix/recipes/
aix_altdisk 'altdisk_by_auto' do
type :auto
value 'equal'
change_bootlist true
action :create
end

### Expected Result:
An error about the undefined method. 

### Actual Result:
```
fittestaix1 undefined method `reset_devices' for Custom resource aix_altdisk from cookbook aix
fittestaix1
fittestaix1 Cookbook Trace:
fittestaix1 ---------------
fittestaix1 /var/chef/cache/cookbooks/aix/providers/altdisk.rb:68:in `block (2 levels) in class_from_file'
fittestaix1 /var/chef/cache/cookbooks/aix/providers/altdisk.rb:63:in `block in class_from_file'


```

**Comment by iennae** [comment]
Thanks for reporting this issue. This has been resolved with version 1.2.1 of this cookbook.
